name: Cypress Swaglab Tests
on:
    workflow_dispatch:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
jobs:
    cypress-run:
        runs-on: ubuntu-22.04
        container: cypress/browsers:node16.16.0-chrome107-ff107-edge
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Cypress run
          uses: cypress-io/github-action@v5
          with:
            build: npm run build
            start: npm start
            browser: chrome
