name: Cypress Swaglab Tests
on:
    workflow_dispatch:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
jobs:
    chrome:
        runs-on: ubuntu-22.04
        name: E2E on Chrome
        steps:
            - uses: actions/checkout@v3
            - uses: cypress-io/github-action@v5
              with:
                  browser: chrome
